### ISSUE TITLE
Transfer Repo to jschaedl 

### ISSUE THREAD

**Issue by sgotre** [jschaedl/sphp-osx#33]
Hi @jschaedl, 
thank you for taking over this project!
I could not transfer it to jschaedl/sphp-osx since this repo already exists.  

Would you please rename yours so i can try again. 

Thank you!

**Comment by jschaedl** [comment]
Hi @sgotre, I deleted jschaedl/sphp-osx. So ready for transfer :-)

**Comment by sgotre** [comment]
HI @jschaedl transfer sequence started... Repo is ready for take off :)

**Comment by jschaedl** [comment]
Thanks @sgotre!
